# Generated by Django 5.2.8 on 2025-12-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific', models.CharField(blank=True, max_length=255, null=True)),
                ('main_common_jp', models.CharField(blank=True, max_length=255, null=True)),
                ('main_common_en', models.CharField(blank=True, max_length=255, null=True)),
                ('itis_tsn', models.IntegerField(blank=True, null=True)),
                ('cites_id', models.IntegerField(blank=True, null=True)),
                ('iucn_id', models.IntegerField(blank=True, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('suborder', models.CharField(blank=True, max_length=255, null=True)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('subfamily', models.CharField(blank=True, max_length=255, null=True)),
                ('genus', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
