# Generated by Django 5.2.8 on 2025-12-03 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='species_app.species')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('scientific', 'Scientific name'), ('common_jp', 'Common name (Japanese)'), ('common_en', 'Common name (English)'), ('others', 'Others')], default='scientific', max_length=20)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='species_app.species')),
            ],
        ),
    ]
