# Generated by Django 5.2.8 on 2025-12-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0002_speciesimage_speciesname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeciesName',
            new_name='Synonyms',
        ),
    ]
