# Generated by Django 5.2.8 on 2025-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0003_rename_speciesname_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='scientific',
            field=models.CharField(default='Unknown', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='synonyms',
            constraint=models.UniqueConstraint(fields=('species', 'type', 'name'), name='unique_species_name_type'),
        ),
    ]
