# Generated by Django 5.2.8 on 2025-12-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species_app', '0004_alter_species_scientific_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Synonyms',
            new_name='Synonym',
        ),
    ]
