# Generated by Django 5.2.16 on 2026-07-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scientific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_main', models.CharField(max_length=200)),
                ('pub_data', models.DateTimeField(verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='CommonJp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=200)),
                ('scientific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.scientific')),
            ],
        ),
        migrations.CreateModel(
            name='CommonEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=200)),
                ('scientific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.scientific')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=200)),
                ('scientific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.scientific')),
            ],
        ),
    ]
