# Generated by Django 5.2.16 on 2026-07-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientific',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
