# Generated by Django 5.2.16 on 2026-07-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_rename_pub_data_scientific_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commonen',
            old_name='synonym',
            new_name='commonen',
        ),
        migrations.RenameField(
            model_name='commonjp',
            old_name='synonym',
            new_name='commonjp',
        ),
    ]
