# Generated by Django 5.2.16 on 2026-07-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_rename_synonym_commonen_commonen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonen',
            name='scientific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_names', to='check.scientific'),
        ),
        migrations.AlterField(
            model_name='commonjp',
            name='scientific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_names', to='check.scientific'),
        ),
    ]
